// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monolrc
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_refresh = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_share = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int date = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int description = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int empty_loading = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int menu_refresh = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int menu_share = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int title = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int titles = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int webview = 2130968581;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int browser_fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int headlines_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int feed_fragment = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int webdetail_share = 2131099649;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int refresh = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int share = 2131034114;
			
			private String()
			{
			}
		}
	}
}
